"""Non-command interaction and privacy-filtered public projections."""

from .diary import PublicDiaryStore
from .inbound import (
    ADAPTERS,
    REPLAY_WINDOW_SECONDS,
    EmailInboundAdapter,
    FeishuInboundAdapter,
    InboundAccepted,
    InboundAuthenticationError,
    InboundChallenge,
    InboundEnvelope,
    InboundIgnored,
    InboundStore,
    QQInboundAdapter,
    TelegramInboundAdapter,
    WebhookInboundAdapter,
    WeChatInboundAdapter,
)
from .integrity import InteractionIntegrity
from .outbound import (
    OUTBOUND_ADAPTERS,
    FeishuOutboundAdapter,
    OutboundRequest,
    QQOutboundAdapter,
    TelegramOutboundAdapter,
    WebhookOutboundAdapter,
    WeChatOutboundAdapter,
)
from .posts import (
    PublicPostCapacityError,
    PublicPostCaptchaError,
    PublicPostConflictError,
    PublicPostQueueFullError,
    PublicPostRateLimitError,
    PublicPostStore,
)
from .projection import PublicProjection
from .store import InteractionStore
from .transport import (
    DeliveryDispatcher,
    DeliveryOutcomeUnknown,
    DeliveryReconciliationRecord,
    DeliveryRecord,
    ProviderStatusEvidence,
    TransportInput,
    TransportRecord,
    TransportStore,
)
from .types import (
    InteractionDecision,
    InteractionRecord,
    PublicDiaryEntry,
    PublicPostInput,
    PublicPostRecord,
)

__all__ = [
    "ADAPTERS",
    "OUTBOUND_ADAPTERS",
    "REPLAY_WINDOW_SECONDS",
    "DeliveryDispatcher",
    "DeliveryOutcomeUnknown",
    "DeliveryReconciliationRecord",
    "DeliveryRecord",
    "EmailInboundAdapter",
    "FeishuInboundAdapter",
    "FeishuOutboundAdapter",
    "InboundAccepted",
    "InboundAuthenticationError",
    "InboundChallenge",
    "InboundEnvelope",
    "InboundIgnored",
    "InboundStore",
    "InteractionDecision",
    "InteractionIntegrity",
    "InteractionRecord",
    "InteractionStore",
    "OutboundRequest",
    "ProviderStatusEvidence",
    "PublicDiaryEntry",
    "PublicDiaryStore",
    "PublicPostCapacityError",
    "PublicPostCaptchaError",
    "PublicPostConflictError",
    "PublicPostInput",
    "PublicPostQueueFullError",
    "PublicPostRateLimitError",
    "PublicPostRecord",
    "PublicPostStore",
    "PublicProjection",
    "QQInboundAdapter",
    "QQOutboundAdapter",
    "TelegramInboundAdapter",
    "TelegramOutboundAdapter",
    "TransportInput",
    "TransportRecord",
    "TransportStore",
    "WeChatInboundAdapter",
    "WeChatOutboundAdapter",
    "WebhookInboundAdapter",
    "WebhookOutboundAdapter",
]
